import Head from "next/head";
import { useRef, useState } from "react";
import React from "react";
import MaskedInput from "react-text-mask";
import {
  arrow,
  belt,
  cloud,
  crosswalk,
  file,
  general,
  light,
  tick,
} from "../components/utils/icon";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="max-w-6xl mx-auto space-y-8 p-6">
          <div className="flex space-x-10">
            <div className="flex-1">
              <video
                className="rounded w-full h-[450px] border shadow-sm"
                controls
              >
                <source
                  src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-1080p.mp4"
                  type="video/mp4"
                ></source>
              </video>
            </div>
            <div className="flex flex-col space-y-5 justify-between">
              <SignBtn />
            </div>
          </div>
          <div className="flex space-x-8">
            <div className="flex-1 flex space-x-8">
              <img
                className="w-80 h-52 rounded object-cover"
                src="https://play-lh.googleusercontent.com/Ip_LzDVSk0AuWeJqJJC6qmcH9jl31FIdfsvl3AcG-lxJNu0R0nqyhTZF1-9izOvEdQ=w526-h296-rw"
                alt="car"
              />
              <div className="p-6 border flex-1 rounded">
                <p className="font-semibold py-2 border-b">
                  Qoidabuzarlik vaqti:{" "}
                  <span className="font-normal text-sm">15.03.2022/14:00</span>
                </p>
                <p className="font-semibold py-2 border-b">
                  Qoidabuzarlik turi:{" "}
                  <span className="font-normal text-sm">Tezlikni oshirish</span>
                </p>
                <p className="font-semibold py-2">Mashina raqami:</p>
                <img
                  className="h-8"
                  src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Pelak_shakhsi-UZ.png/350px-Pelak_shakhsi-UZ.png"
                  alt="car number"
                />
              </div>
            </div>
            <Form />
          </div>
        </div>
      </div>
    </>
  );
}

function SignBtn() {
  const [active, setActive] = useState("lightBtn");
  return (
    <>
      <button
        className={`rounded cursor-pointer ${
          active === "lightBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("lightBtn");
        }}
      >
        <div className="w-24 h-24 pt-3">{light}</div>
      </button>
      <button
        className={`rounded cursor-pointer ${
          active === "crosswalkBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("crosswalkBtn");
        }}
      >
        <div className="w-24 h-24 pt-2">{crosswalk}</div>
      </button>
      <button
        className={`rounded cursor-pointer ${
          active === "beltBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("beltBtn");
        }}
      >
        <div className="w-24 h-24 pt-3">{belt}</div>
      </button>
      <button
        className={`rounded cursor-pointer w-24 h-24 ${
          active === "generalBtn"
            ? "bg-sky-700 text-white"
            : "bg-gray-200 text-sky-700"
        }`}
        onClick={() => {
          setActive("generalBtn");
        }}
      >
        <span className="text-2xl uppercase font-semibold">All</span>
      </button>
    </>
  );
}

function Form() {
  const [value, setValue] = useState({ input: "", select: "UPLOAD" });
  const [selectHide, setSelectHide] = useState(false);

  return (
    <form className="flex flex-col space-y-6">
      <div className="relative select-none cursor-pointer">
        <div
          onClick={() => {
            setSelectHide(!selectHide);
          }}
        >
          <div className="absolute inset-y-0 flex items-center px-3 border-l my-2 right-0">
            <div
              className={`w-3 h-3 fill-sky-500 transition-all duration-500 ${
                selectHide && "rotate-180"
              }`}
            >
              {arrow}
            </div>
          </div>
          <div className="px-3 py-2 w-72 border rounded">{value.select}</div>
        </div>
        {selectHide && (
          <div className="absolute bg-white top-full rounded inset-x-0 border space-y-1 mt-1">
            <div
              className={`${
                value.select === "IP" && "bg-sky-500 text-white rounded-t"
              } p-3`}
              onClick={() => {
                setSelectHide(false);
                setValue((prevValue) => {
                  return { ...prevValue, select: "IP" };
                });
              }}
            >
              IP
            </div>
            <div
              className={`${
                value.select === "UPLOAD" && "bg-sky-500 text-white rounded-b"
              } p-3`}
              onClick={() => {
                setSelectHide(false);
                setValue((prevValue) => {
                  return { ...prevValue, select: "UPLOAD" };
                });
              }}
            >
              UPLOAD
            </div>
          </div>
        )}
      </div>
      {value.select === "IP" ? (
        <MaskedInput
          className="w-72 border px-3 py-2 rounded outline-none focus:border-sky-600"
          mask={[
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
          ]}
          onChange={(e) => {
            setValue((prevValue) => {
              return { ...prevValue, input: e.target.value };
            });
          }}
          placeholder="IP address"
        />
      ) : (
        <InputFile />
      )}
    </form>
  );
}

function InputFile() {
  const browse = useRef();

  // function upLoadFile(name) {
  //   let xhr = new XMLHttpRequest();
  //   xhr.upload.addEventListener("progress", ({ loaded, totall }) => {
  //     let fileLoaded = Math.floor(loaded / totall) * 100;
  //     let fileTotal = Math.floor(totall / 1000);
  //   });
  //   let formData = new FormData(browse);
  //   xhr.send(formData);
  // }

  // const fileHandler = ({ target }) => {
  //   console.log(target.files[0].size);
  //   let file = target.files[0];
  //   if (file) {
  //     let fileName = file.name;
  //     if (fileName.length >= 12) {
  //       let splitName = fileName.split(".");
  //       fileName = splitName[0].substring(0, 12) + "... ." + splitName[1];
  //     }
  //     upLoadFile(fileName);
  //   }
  // };

  return (
    <div className="border w-72 p-4 rounded">
      <div
        className="border-2 cursor-pointer border-dashed flex flex-col fill-sky-700 text-sky-700  items-center justify-center border-sky-700 rounded h-28"
        onClick={() => {
          browse.current.click();
        }}
      >
        <input ref={browse} type={"file"} hidden />
        <div className="w-8 h-8">{cloud}</div>
        <p className="text-sm font-semibold">Browse File to Upload</p>
      </div>
      {/* <ul>
        <li className="bg-gray-200 fill-sky-700 mt-2 py-4 px-3 rounded flex items-center justify-between text-xs">
          <div className="w-4 h-4">{file}</div>
          <div className="w-full ml-4 space-y-3">
            <div className="flex items-center justify-between">
              <span>image_01.png * Uploading</span>
              <span>50%</span>
            </div>
            <div className="h-1.5 w-full bg-white rounded">
              <div className="h-full w-1/2 bg-sky-700 rounded"></div>
            </div>
          </div>
        </li>
        <li className="max-h-[70px] overflow-y-scroll file-input">
          <div className="bg-gray-200 fill-sky-700 mt-2 py-4 px-3 rounded flex items-center justify-between text-xs">
            <div className="flex items-center">
              <div className="w-4 h-4">{file}</div>
              <div>
                <div className="flex flex-col ml-4">
                  <span>image_01.png * Uploading</span>
                  <span className="text-[10px]">70 KB</span>
                </div>
                <div>
                  <div></div>
                </div>
              </div>
            </div>
            <div className="w-4 h-4">{tick}</div>
          </div>
        </li>
      </ul> */}
    </div>
  );
}
