import Head from "next/head";
import FormData from "form-data";
import { useEffect, useRef, useState } from "react";
import React from "react";
import MaskedInput from "react-text-mask";
import { arrow, belt, cloud, crosswalk, light } from "../components/utils/icon";
import axios from "axios";

export default function Home() {
  const [data, setData] = useState("/poster.png");
  console.log(data?.videofile);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="max-w-6xl mx-auto space-y-8 p-6">
          <div className="flex space-x-10">
            <div className="flex-1">
              <img
                className="rounded w-full h-[500px] border shadow-sm"
                src={`http://127.0.0.1:8000/v1/api/rule/${data.id}`}
                alt="camera"
              />
              {/* <Clip url={data?.videofile} /> */}
            </div>
            <div className="flex flex-col space-y-5 justify-between">
              <SignBtn />
            </div>
          </div>
          <div className="flex space-x-8">
            <div className="flex-1 flex space-x-8">
              <img
                className="w-80 h-52 rounded object-cover"
                src="https://play-lh.googleusercontent.com/Ip_LzDVSk0AuWeJqJJC6qmcH9jl31FIdfsvl3AcG-lxJNu0R0nqyhTZF1-9izOvEdQ=w526-h296-rw"
                alt="car"
              />
              <div className="p-6 border border-indigo-500 shadow-lg flex-1 rounded">
                <p className="font-semibold py-2 border-b border-indigo-500">
                  Qoidabuzarlik vaqti:{" "}
                  <span className="font-normal text-sm">15.03.2022/14:00</span>
                </p>
                <p className="font-semibold py-2 border-b border-indigo-500">
                  Qoidabuzarlik turi:{" "}
                  <span className="font-normal text-sm">Tezlikni oshirish</span>
                </p>
                <p className="font-semibold py-2">Mashina raqami:</p>
                <img
                  className="h-8"
                  src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Pelak_shakhsi-UZ.png/350px-Pelak_shakhsi-UZ.png"
                  alt="car number"
                />
              </div>
            </div>
            <Form dataState={setData} />
          </div>
        </div>
      </div>
    </>
  );
}

function Clip({ url }) {
  const videoRef = useRef();

  useEffect(() => {
    videoRef.current?.load();
  }, [url]);

  return (
    <video
      ref={videoRef}
      className="rounded w-full h-[450px] border shadow-sm"
      controls
    >
      <source src={url} />
    </video>
  );
}

function SignBtn() {
  const [active, setActive] = useState("lightBtn");
  return (
    <>
      <button
        className={`rounded cursor-pointer ${
          active === "lightBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("lightBtn");
        }}
      >
        <div className="w-24 h-24 pt-3">{light}</div>
      </button>
      <button
        className={`rounded cursor-pointer ${
          active === "crosswalkBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("crosswalkBtn");
        }}
      >
        <div className="w-24 h-24 pt-2">{crosswalk}</div>
      </button>
      <button
        className={`rounded cursor-pointer ${
          active === "beltBtn"
            ? "bg-sky-700 fill-white"
            : "bg-gray-200 fill-sky-700"
        }`}
        onClick={() => {
          setActive("beltBtn");
        }}
      >
        <div className="w-24 h-24 pt-3">{belt}</div>
      </button>
      <button
        className={`rounded cursor-pointer w-24 h-24 ${
          active === "generalBtn"
            ? "bg-sky-700 text-white"
            : "bg-gray-200 text-sky-700"
        }`}
        onClick={() => {
          setActive("generalBtn");
        }}
      >
        <span className="text-2xl uppercase font-semibold">All</span>
      </button>
    </>
  );
}

function Form({ dataState }) {
  const [value, setValue] = useState({ input: "", select: "UPLOAD" });
  const [selectHide, setSelectHide] = useState(false);
  const browse = useRef();

  const [video, setVideo] = useState({ name: null, path: null });

  let formData = new FormData();

  const submitFileData = (e) => {
    formData.append("name", video.name);
    formData.append("videofile", video.path);

    e.preventDefault();
    axios
      .post("/api/rule/", formData)
      .then((res) => {
        dataState(res.data);
        setVideo({ name: null, path: null });
      })
      .catch((error) => {
        console.log(error);
      });
  };
  return (
    <form className="flex flex-col space-y-6">
      <div className="relative select-none cursor-pointer">
        <div
          onClick={() => {
            setSelectHide(!selectHide);
          }}
        >
          <div className="absolute inset-y-0 flex items-center px-3 border-l my-2 right-0">
            <div
              className={`w-3 h-3 fill-sky-500 transition-all duration-500 ${
                selectHide && "rotate-180"
              }`}
            >
              {arrow}
            </div>
          </div>
          <div className="px-3 py-2 w-72 border border-indigo-500 rounded">
            {value.select}
          </div>
        </div>
        {selectHide && (
          <div className="absolute bg-white top-full rounded inset-x-0 border border-indigo-500 space-y-1 mt-1">
            <div
              className={`${
                value.select === "IP" && "bg-sky-500 text-white rounded-t"
              } p-3`}
              onClick={() => {
                setSelectHide(false);
                setValue((prevValue) => {
                  return { ...prevValue, select: "IP" };
                });
              }}
            >
              IP
            </div>
            <div
              className={`${
                value.select === "UPLOAD" && "bg-sky-500 text-white rounded-b"
              } p-3`}
              onClick={() => {
                setSelectHide(false);
                setValue((prevValue) => {
                  return { ...prevValue, select: "UPLOAD" };
                });
              }}
            >
              UPLOAD
            </div>
          </div>
        )}
      </div>
      {value.select === "IP" ? (
        <MaskedInput
          className="w-72 border border-indigo-500 px-3 py-2 rounded outline-none focus:border-sky-600"
          mask={[
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
            ".",
            /[0-2]/,
            /[0-5]/,
            /[0-5]/,
          ]}
          onChange={(e) => {
            setValue((prevValue) => {
              return { ...prevValue, input: e.target.value };
            });
          }}
          placeholder="IP address"
        />
      ) : (
        <div className="space-y-6">
          <div className="border border-indigo-500 w-72 p-4 rounded">
            <div
              className="border border-indigo-500 cursor-pointer border-dashed flex flex-col fill-sky-700 text-sky-700  items-center justify-center rounded h-28"
              onClick={() => {
                browse.current.click();
              }}
            >
              <input
                onChange={(e) => {
                  setVideo({
                    name: e.target.files[0].name,
                    path: e.target.files[0],
                  });
                }}
                ref={browse}
                type={"file"}
                hidden
              />
              <div className="w-8 h-8">{cloud}</div>
              <p className="text-sm font-semibold">Browse File to Upload</p>
            </div>
          </div>
          {video.name && (
            <div className="flex space-x-1 justify-between items-center">
              <p className="w-40 truncate">{video.name}</p>
              <button
                className="bg-indigo-500 text-sm rounded py-2 px-4 uppercase text-white"
                onClick={submitFileData}
              >
                jonatish
              </button>
            </div>
          )}
        </div>
      )}
    </form>
  );
}
